name: Liaison
favicon: null
layout_spectrum: 0.7444367751013488
typography_spectrum: 0.29699215036816895
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7868680940009654
  lightness: 0.2618817917536944
  saturation: 0.7567097346764058
  rhythmicContrast: 0.3479482573457062
purpose: []
